# Generated by Django 4.0 on 2022-02-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='unique_id',
        ),
    ]
