# Generated by Django 4.0 on 2022-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar-default.gif', null=True, upload_to=''),
        ),
    ]
